namespace Cloudtoid.GatewayCore.Settings
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using Cloudtoid.GatewayCore.Headers;
    using Microsoft.Net.Http.Headers;

    public sealed class UpstreamRequestHeadersSettings
    {
        private static readonly ISet<string> DoNotTransferBaseHeaders =
            new[]
            {
                HeaderNames.Host,
                HeaderNames.Via,
                Names.ExternalAddress,
                Names.ProxyName,
                Names.CallId,
                Names.Forwarded,
                Names.XForwardedFor,
                Names.XForwardedHost,
                Names.XForwardedProto
            }
            .Concat(HeaderTypes.StandardHopByHopeHeaders)
            .Concat(HeaderTypes.ContentHeaders)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        internal UpstreamRequestHeadersSettings(
            bool allowHeadersWithEmptyValue,
            bool allowHeadersWithUnderscoreInName,
            bool includeExternalAddress,
            bool includeProxyName,
            bool discardInboundHeaders,
            bool ignoreVia,
            bool ignoreCorrelationId,
            bool ignoreCallId,
            bool ignoreForwarded,
            bool useXForwarded,
            IReadOnlyDictionary<string, HeaderOverride> overrides,
            ISet<string> discards)
        {
            AllowHeadersWithEmptyValue = allowHeadersWithEmptyValue;
            AllowHeadersWithUnderscoreInName = allowHeadersWithUnderscoreInName;
            IncludeExternalAddress = includeExternalAddress;
            IncludeProxyName = includeProxyName;
            DiscardInboundHeaders = discardInboundHeaders;
            IgnoreVia = ignoreVia;
            IgnoreCorrelationId = ignoreCorrelationId;
            IgnoreCallId = ignoreCallId;
            IgnoreForwarded = ignoreForwarded;
            UseXForwarded = useXForwarded;
            Overrides = overrides;
            Discards = discards;

            DoNotTransferHeaders = DoNotTransferBaseHeaders
                .Concat(overrides.Keys)
                .Concat(discards)
                .ToHashSet(StringComparer.OrdinalIgnoreCase);
        }

        public bool AllowHeadersWithEmptyValue { get; }

        public bool AllowHeadersWithUnderscoreInName { get; }

        public bool IncludeExternalAddress { get; }

        public bool IncludeProxyName { get; }

        public bool DiscardInboundHeaders { get; }

        public bool IgnoreVia { get; }

        public bool IgnoreCorrelationId { get; }

        public bool IgnoreCallId { get; }

        public bool IgnoreForwarded { get; }

        public bool UseXForwarded { get; }

        public IReadOnlyDictionary<string, HeaderOverride> Overrides { get; }

        public ISet<string> Discards { get; }

        /// <summary>
        /// This is a list of headers that should not be passed on to the upstream system as they are.
        /// They can be transferred, but only when they are transformed. This set consists of
        /// <list type="bullet">
        /// <item>Headers generated by an instance of this proxy</item>
        /// <item>Standard hop-by-hop headers. See <see cref="HeaderTypes.StandardHopByHopeHeaders"/> for more information.</item>
        /// <item>Content headers. See <see cref="HeaderTypes.ContentHeaders"/> for more information.</item>
        /// <item><see cref="Overrides"/> headers.</item>
        /// <item><see cref="Discards"/> headers.</item>
        /// </list>
        /// </summary>
        public ISet<string> DoNotTransferHeaders { get; }
    }
}