using System;
using System.Collections.Generic;
using System.Linq;
using Cloudtoid.GatewayCore.Headers;
using Microsoft.Net.Http.Headers;

namespace Cloudtoid.GatewayCore.Settings
{
    public sealed class UpstreamRequestHeadersSettings
    {
        private static readonly ISet<string> DoNotTransferBaseHeaders =
            new[]
            {
                // standard headers
                HeaderNames.Host,
                HeaderNames.Via,
                Names.Forwarded,
                Names.XForwardedFor,
                Names.XForwardedHost,
                Names.XForwardedProto,

                // HTTP/2 pseudo headers (https://datatracker.ietf.org/doc/html/rfc7540#section-8.1.2.3)
                HeaderNames.Method,
                HeaderNames.Authority,
                HeaderNames.Scheme,
                HeaderNames.Path,

                // Gateway Core headers
                Names.ExternalAddress,
                Names.ProxyName
            }
            .Concat(HeaderTypes.StandardHopByHopeHeaders)
            .Concat(HeaderTypes.ContentHeaders)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        internal UpstreamRequestHeadersSettings(
            bool discardInboundHeaders,
            bool discardEmpty,
            bool discardUnderscore,
            bool addExternalAddress,
            bool addProxyName,
            bool skipVia,
            bool skipForwarded,
            bool useXForwarded,
            IReadOnlyDictionary<string, HeaderSettings> appends,
            IReadOnlyDictionary<string, HeaderSettings> overrides,
            ISet<string> discards)
        {
            DiscardEmpty = discardEmpty;
            DiscardUnderscore = discardUnderscore;
            AddExternalAddress = addExternalAddress;
            AddProxyName = addProxyName;
            DiscardInboundHeaders = discardInboundHeaders;
            SkipVia = skipVia;
            SkipForwarded = skipForwarded;
            UseXForwarded = useXForwarded;
            Appends = appends;
            Overrides = overrides;
            Discards = discards;

            DoNotTransferHeaders = DoNotTransferBaseHeaders
                .Concat(overrides.Keys)
                .Concat(discards)
                .ToHashSet(StringComparer.OrdinalIgnoreCase);
        }

        public bool DiscardInboundHeaders { get; }

        public bool DiscardEmpty { get; }

        public bool DiscardUnderscore { get; }

        public bool AddExternalAddress { get; }

        public bool AddProxyName { get; }

        public bool SkipVia { get; }

        public bool SkipForwarded { get; }

        public bool UseXForwarded { get; }

        public IReadOnlyDictionary<string, HeaderSettings> Appends { get; }

        public IReadOnlyDictionary<string, HeaderSettings> Overrides { get; }

        public ISet<string> Discards { get; }

        /// <summary>
        /// This is a list of headers that should not be passed on to the upstream system as they are.
        /// They can be transferred, but only when they are transformed. This set consists of
        /// <list type="bullet">
        /// <item>Headers generated by an instance of this proxy</item>
        /// <item>Standard hop-by-hop headers. See <see cref="HeaderTypes.StandardHopByHopeHeaders"/> for more information.</item>
        /// <item>Content headers. See <see cref="HeaderTypes.ContentHeaders"/> for more information.</item>
        /// <item><see cref="Overrides"/> headers.</item>
        /// <item><see cref="Discards"/> headers.</item>
        /// </list>
        /// </summary>
        public ISet<string> DoNotTransferHeaders { get; }
    }
}