namespace Cloudtoid.GatewayCore.Upstream
{
    using System;
    using System.Collections.Generic;
    using System.Collections.Immutable;
    using System.Linq;
    using System.Net.Http;
    using System.Threading;
    using System.Threading.Tasks;
    using Cloudtoid.GatewayCore.Headers;
    using Microsoft.Extensions.Logging;
    using Microsoft.Net.Http.Headers;
    using static Contract;

    /// <summary>
    /// By inheriting from this class, one can have full control over the outbound upstream request headers. Please consider the following extensibility points:
    /// <list type="number">
    /// <item><description>Inherit from <see cref="RequestHeaderValuesProvider"/>, override its methods, and register it with DI; or</description></item>
    /// <item><description>Implement <see cref="IRequestHeaderValuesProvider"/> and register it with DI; or</description></item>
    /// <item><description>Inherit from <see cref="RequestHeaderSetter"/>, override its methods, and register it with DI; or</description></item>
    /// <item><description>Implement <see cref="IRequestHeaderSetter"/> and register it with DI</description></item>
    /// </list>
    /// </summary>
    /// <example>
    /// Dependency Injection registrations:
    /// <list type="bullet">
    /// <item><description><c>TryAddSingleton&lt;<see cref="IRequestHeaderValuesProvider"/>, MyRequestHeaderValuesProvider&gt;()</c></description></item>
    /// <item><description><c>TryAddSingleton&lt;<see cref="IRequestHeaderSetter"/>, MyRequestHeaderSetter&gt;()</c></description></item>
    /// </list>
    /// </example>
    public partial class RequestHeaderSetter : IRequestHeaderSetter
    {
        private const char Comma = ',';

        /// <summary>
        /// This is a list of headers that should not be passed on to the upstream system. It consists of
        /// <list type="bullet">
        /// <item>Headers generated by an instance of this proxy</item>
        /// <item>Standard hop-by-hop headers. See <see cref="HeaderTypes.StandardHopByHopeHeaders"/> for more information.</item>
        /// <item>Content headers. See <see cref="HeaderTypes.ContentHeaders"/> for more information.</item>
        /// </list>
        /// </summary>
        protected static readonly ISet<string> HeaderTransferBlacklist =
            new[]
            {
                    HeaderNames.Host,
                    HeaderNames.Via,
                    Names.ExternalAddress,
                    Names.ProxyName,
                    Names.CallId,
                    Names.Forwarded,
                    Names.XForwardedFor,
                    Names.XForwardedHost,
                    Names.XForwardedProto
            }
            .Concat(HeaderTypes.StandardHopByHopeHeaders)
            .Concat(HeaderTypes.ContentHeaders)
            .ToHashSet(StringComparer.OrdinalIgnoreCase);

        private readonly HeaderSanetizer sanetizer;

        public RequestHeaderSetter(
            IRequestHeaderValuesProvider provider,
            ILogger<RequestHeaderSetter> logger)
        {
            Provider = CheckValue(provider, nameof(provider));
            Logger = CheckValue(logger, nameof(logger));
            sanetizer = new HeaderSanetizer(logger);
        }

        protected IRequestHeaderValuesProvider Provider { get; }

        protected ILogger<RequestHeaderSetter> Logger { get; }

        public virtual Task SetHeadersAsync(
            ProxyContext context,
            HttpRequestMessage upstreamRequest,
            CancellationToken cancellationToken)
        {
            CheckValue(context, nameof(context));
            CheckValue(upstreamRequest, nameof(upstreamRequest));

            cancellationToken.ThrowIfCancellationRequested();

            AddDownstreamRequestHeadersToUpstream(context, upstreamRequest);
            AddViaHeader(context, upstreamRequest);
            AddHostHeader(context, upstreamRequest);
            AddExternalAddressHeader(context, upstreamRequest);
            AddForwardedHeaders(context, upstreamRequest);
            AddCorrelationIdHeader(context, upstreamRequest);
            AddCallIdHeader(context, upstreamRequest);
            AddProxyNameHeader(context, upstreamRequest);
            AddExtraHeaders(context, upstreamRequest);

            return Task.CompletedTask;
        }

        protected virtual void AddDownstreamRequestHeadersToUpstream(
            ProxyContext context,
            HttpRequestMessage upstreamRequest)
        {
            var options = context.ProxyUpstreamRequestHeadersSettings;
            if (options.IgnoreAllDownstreamHeaders)
                return;

            var headers = context.Request.Headers;
            var allowHeadersWithEmptyValue = options.AllowHeadersWithEmptyValue;
            var allowHeadersWithUnderscoreInName = options.AllowHeadersWithUnderscoreInName;
            var correlationIdHeader = context.CorrelationIdHeader;
            var headersWithOverride = options.OverrideNames;
            var nonStandardHopByHopHeaders = GetNonStandardHopByHopHeaders(context);

            foreach (var header in headers)
            {
                var name = header.Key;

                if (!sanetizer.IsValid(
                    name,
                    header.Value,
                    allowHeadersWithEmptyValue,
                    allowHeadersWithUnderscoreInName))
                    continue;

                if (HeaderTransferBlacklist.Contains(name))
                    continue;

                if (nonStandardHopByHopHeaders.Contains(name))
                    continue;

                // If it has an override, we will not transfer its value
                if (headersWithOverride.Contains(name))
                    continue;

                if (name.EqualsOrdinalIgnoreCase(correlationIdHeader))
                    continue;

                AddHeaderValues(context, upstreamRequest, name, header.Value);
            }
        }

        protected virtual void AddHostHeader(ProxyContext context, HttpRequestMessage upstreamRequest)
        {
            if (context.ProxyUpstreamRequestHeadersSettings.IgnoreHost)
                return;

            upstreamRequest.Headers.TryAddWithoutValidation(
                HeaderNames.Host,
                context.Host);
        }

        protected virtual void AddExternalAddressHeader(ProxyContext context, HttpRequestMessage upstreamRequest)
        {
            if (!context.ProxyUpstreamRequestHeadersSettings.IncludeExternalAddress)
                return;

            var clientAddress = GetRemoteIpAddressOrDefault(context);
            if (clientAddress is null)
                return;

            AddHeaderValues(
                context,
                upstreamRequest,
                Names.ExternalAddress,
                clientAddress);
        }

        protected virtual void AddCorrelationIdHeader(ProxyContext context, HttpRequestMessage upstreamRequest)
        {
            if (context.ProxyUpstreamRequestHeadersSettings.IgnoreCorrelationId)
                return;

            AddHeaderValues(
                context,
                upstreamRequest,
                context.CorrelationIdHeader,
                context.CorrelationId);
        }

        protected virtual void AddCallIdHeader(ProxyContext context, HttpRequestMessage upstreamRequest)
        {
            if (context.ProxyUpstreamRequestHeadersSettings.IgnoreCallId)
                return;

            AddHeaderValues(
                context,
                upstreamRequest,
                Names.CallId,
                context.CallId);
        }

        protected virtual void AddProxyNameHeader(ProxyContext context, HttpRequestMessage upstreamRequest)
        {
            if (!context.ProxyUpstreamRequestHeadersSettings.IncludeProxyName)
                return;

            AddHeaderValues(
                context,
                upstreamRequest,
                Names.ProxyName,
                context.ProxyName);
        }

        protected virtual void AddExtraHeaders(ProxyContext context, HttpRequestMessage upstreamRequest)
        {
            foreach (var header in context.ProxyUpstreamRequestHeadersSettings.Overrides)
            {
                if (header.HasValues)
                    upstreamRequest.Headers.TryAddWithoutValidation(header.Name, header.GetValues(context));
            }
        }

        protected virtual void AddHeaderValues(
            ProxyContext context,
            HttpRequestMessage upstreamRequest,
            string name,
            params string[] downstreamValues)
        {
            if (Provider.TryGetHeaderValues(context, name, downstreamValues, out var upstreamValues) && upstreamValues != null)
            {
                upstreamRequest.Headers.TryAddWithoutValidation(name, upstreamValues);
                return;
            }

            Logger.LogInformation(
                "Header '{0}' is not added. This was instructed by {1}.{2}.",
                name,
                nameof(IRequestHeaderValuesProvider),
                nameof(IRequestHeaderValuesProvider.TryGetHeaderValues));
        }

        /// <summary>
        /// Except for the standard hop-by-hop headers (Keep-Alive, Transfer-Encoding, TE, Connection, Trailer, Upgrade,
        /// Proxy-Authorization and Proxy-Authenticate), any hop-by-hop headers used by the message must be listed in the
        /// Connection header, so that the first proxy knows it has to consume them and not forward them further.
        /// Standard hop-by-hop headers can be listed too (it is often the case of Keep-Alive, but this is not mandatory).
        /// See <a href="https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Connection">here</a> for more information.
        /// </summary>
        private static ISet<string> GetNonStandardHopByHopHeaders(ProxyContext context)
        {
            if (context.Request.Headers.TryGetValue(HeaderNames.Connection, out var values) && values.Count > 0)
            {
                var headers = values.SelectMany(v => v.Split(Comma, StringSplitOptions.RemoveEmptyEntries).Select(v => v.Trim()));
                return new HashSet<string>(headers, StringComparer.OrdinalIgnoreCase);
            }

            return ImmutableHashSet<string>.Empty;
        }

        private static string? GetRemoteIpAddressOrDefault(ProxyContext context)
            => context.HttpContext.Connection.RemoteIpAddress?.ToString();
    }
}
